#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
    # 1) Basic Setup
    # 2) Desktop Environment
    # 3) Accessories Apps
    # 4) Development Apps
    # 5) Office Apps
    # 6) System Apps
    # 7) Graphics Apps
    # 8) Internet Apps
    # 9) Audio Apps
    #10) Video Apps
    #11) Games
    #12) LAMP
    #13) Fonts
    #14) Fonts Configuration
    #15) Clean Orphan Packages
    MAINMENU="1-15"
#}}}
#CUSTOMREPO {{{
    # 1) Elementary
    # 2) Globus Preview
    # 3) GNOME 3
    # 4) Jdownloader
    # 5) Medibuntu
    # 6) Themes/Icons
    # 7) Ubuntu-tweak
    # 8) Webupd8
    CUSTOMREPO="1-8"
#}}}
#VIDEOCARD {{{
    # 1) ATI
    # 2) nVidia
    # 3) Virtualbox
    # 4) Skip
    VIDEOCARD=4
#}}}
#DESKTOP ENVIRONMENT {{{
    # 1) GNOME
    # 2) KDE
    # 3) Unity
    DESKTOPENV=3

    #GNOME {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) GNOME Shell Extensions
        # 4) GNOME Shell Themes
        # 5) GNOME Activity Journal
        # 6) Gloobus-preview
        # 7) Ubuntu-tweak
        GNOME_OPTIONS="1-7"
        #GNOME EXTENSIONS {{{
            # 1) gpaste
            # 2) media-player
            # 3) noa11y
            # 4) weather
            GNOME_EXTENSIONS="1-4"
        #}}}
        #GNOME SHELL THEMES {{{
            # 1) eOS
            # 2) Dark Shine
            # 3) Faience
            # 4) Nord
            GNOME_SHELL_THEMES="1-4"
        #}}}
    #}}}
    #KDE {{{
        # 1) Apper
        # 2) Bangarang
        # 3) Choqok
        # 4) Digikam
        # 5) K3b
        # 6) KDE Icons [Rosa, KFaenza]
        # 7) Plasma Themes [Caledonia, Produkt, Ronak]
        # 8) Yakuake
        KDE_OPTIONS=""
    #}}}
    #UNITY {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) Gloobus-preview
        # 4) Ubuntu-tweak
        # 5) Unity Lens
        UNITY_OPTIONS="1-4"
        #UNITY LENS {{{
            # 1) unity-lens-bookmarks
            # 2) unity-lens-photo
            # 3) unity-lens-askubuntu
            # 4) unity-lens-cooking
            # 5) unity-lens-graphicdesign
            # 6) unity-lens-torrents
            # 7) unity-lens-wikipedia
            # 8) unity-scope-calculator
            # 9) unity-scope-cities
            #10) unity-scope-colourlovers
            #11) unity-scope-deviantart
            #12) unity-scope-grooveshark
            #13) unity-scope-rottentomatoes
            UNITY_LENS="1 2 6 8 12"
        #}}}
    #}}}

    #GNOME ICONS {{{
        # 1) Awoken
        # 2) Faenza
        # 3) Faenza-Cupertino
        # 4) Faience
        # 5) Elementary
        GNOME_ICONS="2-5"
    #}}}
    #GTK THEMES {{{
        # 1) Bluebird
        # 2) eGTK
        # 3) Holo
        # 4) Adwaita-X Dark
        # 5) Adwaita-X Light
        # 6) Zukini
        # 7) Zukitwo
        GNOME_THEMES="1-7"
    #}}}
#}}}
#ACCESSORIES {{{
    # 1) Cairo Dock
    # 2) Conky + CONKY-colors
    # 3) Deepin Scrot
    # 4) Dockbarx
    # 5) Docky
    # 6) Galculator/Speedcrunch
    # 7) Gnome-Pie
    # 8) Guake
    # 9) Kupfer
    #10) Pyrenamer
    #11) Shutter
    #12) Synapse
    #13) Terminator
    #14) Zim
    ACCESSORIES_OPTIONS="3 7 9 13"
#}}}
#DEVELOPEMENT {{{
    # 1) Aptana Studio
    # 2) Bluefish
    # 3) Eclipse
    # 4) Emacs
    # 5) Gvim
    # 6) Geany
    # 7) IntelliJ IDEA
    # 8) Netbeans
    # 9) Oracle Java
    #10) QT Creator
    #11) Sublime Text 2
    #12) Debugger Tools [Valgrind, Gdb, Splint, Tidyhtml, Pyflakes, Jsl]
    #13) MySQL Workbench
    #14) Meld
    DEVELOPMENT_OPTIONS="5"
#}}}
#OFFICE {{{
    # 1) LibreOffice
    # 2) GnomeOffice [Abiword, Gnumeric]
    # 3) Latex + Texmaker
    # 4) CHM Viewer
    # 5) GCStar
    # 6) Homebank
    # 7) Impressive
    # 8) Nitrotasks
    # 9) OCRFeeder
    #10) Xmind
    #11) Zathura
    OFFICE_OPTIONS="1 8 9"
#}}}
#SYSTEM TOOLS {{{
    # 1) Gparted
    # 2) Grsync
    # 3) Htop
    # 4) Virtualbox
    # 5) Webmin
    # 6) Wine
    SYSTEMTOOLS_OPTIONS="2 3"
#}}}
#GRAPHICS {{{
    # 1) Blender
    # 2) Gimp
    # 3) Gimp-plugins
    # 4) Gthumb
    # 5) Inkscape
    # 6) MComix
    # 7) Mypaint
    # 8) Scribus
    # 9) Shotwell
    GRAPHICS_OPTIONS="2-7 9"
#}}}
#INTERNET {{{
    # 1) Dropbox
    # 2) Chromium
    # 3) Google Earth
    # 4) Google Chrome
    # 5) Jdownloader
    # 6) Irssi
    # 7) Midori
    # 8) Mozilla Firefox
    # 9) Mozilla Thunderbird
    #10) Emesene
    #11) Pidgin
    #12) Remmina
    #13) Skype
    #14) Teamspeak
    #15) Teamviewer
    #16) Trasmission
    #17) X-Chat/Konversation
    INTERNET_OPTIONS="1 2 5 7"
#}}}
#LAMP {{{
    LAMP="y"
#}}}
#AUDIO {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Decibel
    # 6) Musique
    # 7) Nuvola
    # 8) Rhythmbox
    # 9) Spotify
    #10) Tomahawk
    #11) Soundconverter
    #12) Puddletag
    #13) Audacity
    #14) MIDI
    #15) Codecs
    AUDIO_OPTIONS="4 11 15"
#}}}
#VIDEO {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Rosa Media Player
    # 6) SMplayer
    # 7) VLC
    # 8) XBMC
    # 9) Arista
    #10) Transmageddon
    #11) Kdenlive
    #12) Openshot
    #13) Pitivi
    #14) Kazam
    #15) Codecs
    VIDEO_OPTIONS="7 8 15"
#}}}
#FONTS {{{
    # 1) ttf-dejavu
    # 2) ttf-google-webfonts
    # 3) ttf-liberation
    # 4) ttf-ms-fonts
    FONTS_OPTIONS="1 3 4"
    GOOGLE_FONTS="y"
#}}}
