#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
    # 1) Basic Setup
    # 2) Desktop Environment
    # 3) Accessories Apps
    # 4) Development Apps
    # 5) Office Apps
    # 6) System Apps
    # 7) Graphics Apps
    # 8) Internet Apps
    # 9) Audio Apps
    #10) Video Apps
    #11) Games
    #12) LAMP
    #13) Fonts
    #14) Fonts Configuration
    #15) Clean Orphan Packages
    MAINMENU="1-15"
#}}}
#CUSTOMREPO {{{
    # 1) Elementary
    # 2) Globus Preview
    # 3) GNOME 3
    # 4) Jdownloader
    # 5) Medibuntu
    # 6) Themes/Icons
    # 7) Ubuntu-tweak
    # 8) Webupd8
    CUSTOMREPO="1-8"
#}}}
#VIDEOCARD {{{
    # 1) ATI
    # 2) nVidia
    # 3) Virtualbox
    # 4) Skip
    VIDEOCARD=4
#}}}
#DESKTOP ENVIRONMENT {{{
    # 1) Pantheon
    # 2) Gnome Shell
    # 3) KDE
    # 4) Unity
    DESKTOPENV=1

    #GNOME {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) Ubuntu-tweak
        GNOME_OPTIONS="1-3"
    #}}}
    #KDE {{{
        # 1) Apper
        # 2) Bangarang
        # 3) Choqok
        # 4) Digikam
        # 5) K3b
        # 6) KDE Icons [Rosa, KFaenza]
        # 7) Plasma Themes [Caledonia, Produkt, Ronak]
        # 8) Yakuake
        KDE_OPTIONS=""
    #}}}
    #UNITY {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) Ubuntu-tweak
        # 4) Unity Lens
        UNITY_OPTIONS="1-4"
        #UNITY LENS {{{
            # 1) unity-lens-bookmarks
            # 2) unity-lens-photo
            # 3) unity-lens-askubuntu
            # 4) unity-lens-cooking
            # 5) unity-lens-graphicdesign
            # 6) unity-lens-news
            # 7) unity-lens-torrents
            # 8) unity-lens-wikipedia
            # 9) unity-scope-calculator
            #10) unity-scope-cities
            #11) unity-scope-colourlovers
            #12) unity-scope-deviantart
            #13) unity-scope-grooveshark
            #14) unity-scope-rottentomatoes
            UNITY_LENS="1 2 7 9 13"
        #}}}
    #}}}

    #GNOME ICONS {{{
        # 1) Faenza
        # 2) Faenza-Cupertino
        # 3) Faience
        # 4) Elementary
        GNOME_ICONS="1-4"
    #}}}
    #GTK THEMES {{{
        # 1) Greybird
        # 2) eGTK
        # 3) Faience
        # 4) Adwaita-X Dark
        # 5) Adwaita-X Light
        GNOME_THEMES="1-5"
    #}}}
#}}}
#ACCESSORIES {{{
    # 1) Cairo Dock
    # 2) Conky + CONKY-colors
    # 3) Deepin Scrot
    # 4) Dockbarx
    # 5) Docky
    # 6) Galculator/Speedcrunch
    # 7) Gnome-Pie
    # 8) Guake
    # 9) Kupfer
    #10) Pyrenamer
    #11) Shutter
    #12) Synapse
    #13) Terminator
    #14) Zim
    ACCESSORIES_OPTIONS="3 7 9 13"
#}}}
#DEVELOPEMENT {{{
    # 1) Aptana Studio
    # 2) Bluefish
    # 3) Eclipse
    # 4) Emacs
    # 5) Gvim
    # 6) Geany
    # 7) IntelliJ IDEA
    # 8) Netbeans
    # 9) Oracle Java
    #10) QT Creator
    #11) Sublime Text 2
    #12) Debugger Tools [Valgrind, Gdb, Splint, Tidyhtml, Pyflakes, Jsl]
    #13) MySQL Workbench
    #14) Meld
    DEVELOPMENT_OPTIONS="5"
#}}}
#OFFICE {{{
    # 1) LibreOffice
    # 2) GnomeOffice [Abiword, Gnumeric]
    # 3) GWoffice
    # 4) Latex + Texmaker
    # 5) CHM Viewer
    # 6) GCStar
    # 7) Homebank
    # 8) Impressive
    # 9) Nitrotasks
    #10) OCRFeeder
    #11) Xmind
    #12) Zathura
    OFFICE_OPTIONS="8 9"
#}}}
#SYSTEM TOOLS {{{
    # 1) Gparted
    # 2) Grsync
    # 3) Htop
    # 4) Virtualbox
    # 5) Webmin
    # 6) Wine
    SYSTEMTOOLS_OPTIONS="2 3"
#}}}
#GRAPHICS {{{
    # 1) Blender
    # 2) Gimp
    # 3) Gimp-plugins
    # 4) Gthumb
    # 5) Inkscape
    # 6) MComix
    # 7) Mypaint
    # 8) Scribus
    # 9) Shotwell
    #10) XnViewMP
    GRAPHICS_OPTIONS="2-7 9"
#}}}
#INTERNET {{{
    # 1) Browser
    # 2) Download|Fileshare
    # 3) Email|RSS
    # 4) Instant Messaging
    # 5) IRC
    # 6) Mapping Tools
    # 7) VNC|Desktop Share
    INTERNET_OPTIONS="1-7"
    #BROWSER {{{
        # 1) Chromium
        # 2) Google Chrome
        # 3) Midori|Rekonq
        # 4) Mozilla Firefox
        # 5) Opera
        BROWSERS_OPTIONS="2 4"
    #}}}
    #DOWNLOAD|FILESHARE {{{
        # 1) Deluge
        # 2) Dropbox
        # 3) Jdownloader
        # 4) Nitroshare
        # 5) Sparkleshare
        # 6) Steadyflow
        # 7) Trasmission
        DOWNLOAD_OPTIONS="3"
    #}}}
    #EMAIL|RSS {{{
        # 1) Mozilla Thunderbird
        # 2) Liferea
        # 3) LightRead
        EMAIL_OPTIONS="3"
    #}}}
    #IM {{{
        # 1) Emesene
        # 2) Google Talk-Plugin
        # 3) Pidgin
        # 4) Skype
        # 5) Teamspeak
        IM_OPTIONS="2 4"
    #}}}
    #IRC {{{
        # 1) Irssi
        # 2) X-Chat|Quassel
        IRC_OPTIONS=""
    #}}}
    #MAPPING {{{
        # 1) Google Earth
        # 2) NASA World Wind
        MAPPING_OPTIONS=""
    #}}}
    #VNC|Desktop Share {{{
        # 1) Remmina
        # 2) Teamviewer
        VNC_OPTIONS=""
    #}}}
#}}}
#AUDIO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  AUDIO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Deadbeef
    # 6) Exaile
    # 7) Musique
    # 8) Nuvola
    # 9) Rhythmbox
    #10) Radiotray
    #11) Spotify
    #12) Tomahawk
    #13) Timidity++
    AUDIO_PLAYER_OPTIONS="4"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Soundconverter|Soundkonverter
    # 2) Puddletag
    # 3) Audacity
    # 4) OcenAudio
    AUDIO_EDITOR_OPTIONS="1"
  #}}}
#}}}
#VIDEO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  VIDEO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Miro
    # 6) SMplayer
    # 7) VLC
    # 8) XBMC
    VIDEO_PLAYER_OPTIONS="7 8"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Avidemux
    # 2) Arista
    # 3) Transmageddon
    # 4) Kdenlive
    # 5) Openshot
    # 6) Pitivi
    # 7) Kazam
    VIDEO_EDITOR_OPTIONS="3"
  #}}}
#}}}
#WEBSERVER {{{
  # 1) LAMP - APACHE, MYSQL & PHP + ADMINER
  # 2) LAPP - APACHE, POSTGRESQL & PHP + ADMINER
  WEBSERVER="1"
#}}}
#FONTS {{{
    # 1) ttf-dejavu
    # 2) ttf-google-webfonts
    # 3) ttf-liberation
    # 4) ttf-ms-fonts
    FONTS_OPTIONS="1 3 4"
    GOOGLE_FONTS="y"
#}}}
